const app=document.querySelector('#app');const title=document.querySelector('#title');
const orders=[
{id:'18A26B01',cliente:'MARIA SILVA',produto:'REFRIGERADOR ELECTROLUX',status:'AGUARDANDO ANÁLISE',tecnico:'CARLOS'},
{id:'18A26B02',cliente:'JOÃO PEREIRA',produto:'TV SAMSUNG 55"',status:'AGUARDANDO APROVAÇÃO',tecnico:'RICARDO'},
{id:'18A26B03',cliente:'ANA COSTA',produto:'MICRO-ONDAS CONSUL',status:'AGUARDANDO CONSERTO',tecnico:'CARLOS'},
{id:'18A26B04',cliente:'PAULO SOUZA',produto:'AR-CONDICIONADO LG',status:'PRONTO PARA ENTREGA',tecnico:'MARCOS'}];
const views={
dashboard:()=>`<div class="grid"><div class="card metric"><span>OS em aberto</span><b>42</b></div><div class="card metric"><span>Aguardando análise</span><b>11</b></div><div class="card metric"><span>Aguardando aprovação</span><b>8</b></div><div class="card metric"><span>Prontas para entrega</span><b>7</b></div></div><div class="section-title"><h2>Ordens de Serviço recentes</h2><button class="secondary" onclick="render('os')">Ver todas</button></div>${tableOrders()}`,
os:()=>`<div class="section-title"><h2>Ordens de Serviço</h2><button class="primary" onclick="render('nova-os')">+ Gerar OS</button></div>${tableOrders()}`,
'nova-os':()=>`<div class="card"><div class="section-title"><h2>Nova Ordem de Serviço</h2><span class="status">RASCUNHO</span></div><div class="form-grid"><div class="field"><label>CLIENTE *</label><input placeholder="Buscar ou cadastrar cliente"></div><div class="field"><label>TELEFONE</label><input placeholder="(27) 99999-9999"></div><div class="field"><label>TIPO DE PRODUTO *</label><select><option>Selecione</option><option>TV</option><option>REFRIGERADOR</option><option>AR-CONDICIONADO</option><option>MICRO-ONDAS</option></select></div><div class="field"><label>MARCA / MODELO</label><input placeholder="Marca e modelo"></div><div class="field"><label>TIPO DE ATENDIMENTO</label><select><option>INTERNO</option><option>EXTERNO</option></select></div><div class="field"><label>LOCAL DO PRODUTO</label><select><option>LABORATÓRIO</option><option>CONSUMIDOR</option></select></div><div class="field wide"><label>DEFEITO RELATADO *</label><textarea placeholder="Descrição informada pelo cliente"></textarea></div><div class="field wide"><label>OBSERVAÇÕES INTERNAS — NÃO IMPRIMIR</label><textarea placeholder="Uso interno da equipe"></textarea></div></div><div class="actions"><button class="primary" onclick="fakeSave()">Salvar OS</button><button class="secondary" onclick="render('os')">Cancelar</button></div></div>`,
clientes:()=>moduleView('Clientes','Ficha 360º, equipamentos vinculados, histórico de OS e contatos do cliente.'),
oficina:()=>moduleView('Oficina','Fila técnica, equipamentos, pareceres, documentação técnica e acompanhamento do reparo.'),
estoque:()=>moduleView('Estoque','Peças, movimentações, estoque em poder do técnico e rastreabilidade por OS.'),
financeiro:()=>moduleView('Financeiro','Orçamentos, pagamentos, caixa, formas de pagamento e acompanhamento financeiro da OS.'),
testes:()=>`<div class="section-title"><h2>Testes de Funções</h2><span class="status">HOMOLOGAÇÃO</span></div><div class="card"><div class="test"><div><strong>Atendimento / Ordem de Serviço</strong><span>Cadastro, geração de OS, navegação e situação</span></div><span class="ok">EM TESTE</span></div></div><div class="card" style="margin-top:12px"><div class="test"><div><strong>Perfis de usuário</strong><span>Gestor, atendente e técnico</span></div><span class="status">PREPARADO</span></div></div><div class="card" style="margin-top:12px"><div class="test"><div><strong>Supabase / dados reais de homologação</strong><span>Integração será ativada após configuração das variáveis do projeto</span></div><span class="status">PENDENTE</span></div></div>`};
function tableOrders(){return `<table><thead><tr><th>OS</th><th>Cliente</th><th>Produto</th><th>Situação</th><th>Técnico</th></tr></thead><tbody>${orders.map(o=>`<tr><td><b>${o.id}</b></td><td>${o.cliente}</td><td>${o.produto}</td><td><span class="status">${o.status}</span></td><td>${o.tecnico}</td></tr>`).join('')}</tbody></table>`}
function moduleView(name,desc){return `<div class="modules"><div class="card module-card"><h3>${name}</h3><p>${desc}</p></div><div class="card module-card"><h3>Dados fictícios</h3><p>Ambiente isolado para homologação, sem informações reais de clientes.</p></div><div class="card module-card"><h3>Próxima evolução</h3><p>Conectar persistência, permissões e fluxos detalhados do Backlog Mestre.</p></div></div>`}
function render(view){title.textContent=view==='nova-os'?'Nova Ordem de Serviço':document.querySelector(`[data-view="${view}"]`)?.textContent||'VoxAssist';app.innerHTML=(views[view]||views.dashboard)();document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===view));}
function fakeSave(){alert('OS fictícia salva para homologação. Persistência no Supabase ainda não ativada.');render('os')}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>render(b.dataset.view));document.querySelector('#newOs').onclick=()=>render('nova-os');render('dashboard');