const test=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');
const source=fs.readFileSync(require('node:path').join(__dirname,'../os-documents-tab-v0909.js'),'utf8');
function setup(api){const printed=[];const ctx={window:{getActiveCompanyBranding:async()=>({trade_name:'VOX',city:'Serra'})},document:{},state:{},api,URL,location:{href:'https://vox.example/'},setTimeout(){},toast(){},console};ctx.window.vxPrintShell=(title,body)=>printed.push({title,body});vm.runInNewContext(source.replace('const baseRender=window.renderOsDetail;','window.__reportTest={buildDataSnapshot,buildVoxReportBody,buildAssurantBody,reopenEmission,collectReportExtra};const baseRender=window.renderOsDetail;'),ctx);return {...ctx.window.__reportTest,printed};}
const os={id:'os-id',company_id:'company',os_number:'VOX123',manufacturer_os_number:'FAB456',opened_at:'2026-10-01T12:00:00Z',clients:{name:'Cliente <script>',phone_primary:'2799999',address:'Rua A',address_number:'10',city:'Serra'},equipments:{brand:'Marca',model:'Modelo',serial_number:'SER123'},reported_defect:'Não liga',diagnosed_defect:'Fonte avariada',profiles:{full_name:'Técnico'}};
function api(path){if(path.startsWith('service_orders'))return Promise.resolve([os]);if(path.startsWith('os_parts'))return Promise.resolve([{part_code:'P1',description:'Fonte <x>',quantity:2,unit_value:50}]);if(path.startsWith('os_financial'))return Promise.resolve([{labor_value:100,freight_value:20,discount_value:10}]);throw Error(path);}
test('prefill preserves OS identity and calculates the same complete budget',async()=>{const t=setup(api);const d=await t.buildDataSnapshot('os-id','PARECER_VOX',{});assert.equal(d.os_numero,'VOX123');assert.equal(d.manufacturer_os_number,'FAB456');assert.equal(d.totalValor,210);assert.equal(d.telefone,'2799999');assert.match(d.endereco,/Rua A, 10/);assert.equal(d.responsavel,'Técnico');assert.equal(d.pecas.length,1);const factory=await t.buildDataSnapshot('os-id','HISENSE',{});assert.equal(factory.os_numero,'FAB456');});
test('VOX rendering escapes user text, includes parts and selected signature, omits empty diagnosis',async()=>{const t=setup(api);const d=await t.buildDataSnapshot('os-id','PARECER_VOX',{parecerTecnico:'<script>alert(1)</script>',responsavel:'André'});const body=t.buildVoxReportBody(d);assert.ok(!body.includes('<script>'));assert.match(body,/&lt;script&gt;/);assert.match(body,/Fonte &lt;x&gt;/);assert.match(body,/André · Técnico responsável/);assert.match(body,/210,00/);const empty=t.buildVoxReportBody({...d,parecerTecnico:'',diagnosticoTec:''});assert.ok(!empty.includes('<h3>PARECER TÉCNICO</h3>'));});
test('reopening renders the archived snapshot instead of refetching current OS',()=>{const t=setup(()=>{throw Error('must not fetch')});t.reopenEmission({document_type:'PARECER_VOX',document_version:2,data_snapshot:{cliente:'Nome arquivado',parecerTecnico:'Diagnóstico original',pecas:[],responsavel:'Original'}});assert.match(t.printed[0].body,/Nome arquivado/);assert.match(t.printed[0].body,/Diagnóstico original/);});
test('financial read failure aborts instead of generating a false zero budget',async()=>{const t=setup(path=>path.startsWith('os_financial')?Promise.reject(Error('sem acesso')):api(path));await assert.rejects(t.buildDataSnapshot('os-id','PARECER_VOX',{}),/sem acesso/);});

test('Assurant uses valid four-cell rows and skips empty photo frames',()=>{const t=setup(api);const body=t.buildAssurantBody({assistenciaTec:'VOX SERRA',cnpj:'123',numeroSerie:'SER',sinistro:'SIN',produtoMarca:'Marca',modeloProduto:'Modelo',fotos:[{dataUrl:''}],cotacaoImgs:['',''],responsavel:'Nome longo do técnico responsável',cidade:'Serra',dataParecer:'04/10/2026'});assert.ok(!body.includes('<tr><tr>'));assert.ok(!body.includes('<figure>'));assert.match(body,/<tr><th>Assistência<\/th><td>VOX SERRA<\/td><th>CNPJ<\/th><td>123<\/td><\/tr>/);assert.ok(!body.includes('position:absolute'));assert.ok(!body.includes('width:210mm'));assert.match(body,/assurant-signatures/);});
test('Assurant includes attached evidence with escaped captions',()=>{const t=setup(api);const body=t.buildAssurantBody({fotos:[{dataUrl:'data:image/png;base64,AAAA',legenda:'Peça <x>'}],cotacaoImgs:[''],residenciaImg:''});assert.equal((body.match(/<figure>/g)||[]).length,1);assert.match(body,/Peça &lt;x&gt;/);});
